#!/bin/bash
echo -e "\033[1;36m ¡ESTA ES TU INFORMACIÓN!\033[0m"
echo ""
echo -ne "TU DOMINIO NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "TU KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/Gatesccn/projecdemo/main/Slowdns/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SU KEY SE GUARDO EN  /root/server.pub\033[0m"
echo -e "\033[1;33mGuardado para el futuro!\033[0m"
echo ""
read -p "Pressione [Enter] para SALIR a menu o CTRL+C para sair"
slowdns
